### ISSUE TITLE
re-index search

### ISSUE THREAD

**Issue by rayrshah** [rayrshah/3T#67]

**Comment by niravpateldev** [comment]
Done

**Comment by rayrshah** [comment]
@adam-td what was the search term that was showing up results?

**Comment by kiran-td** [comment]
It was adobe @rayrshah

**Comment by adam-td** [comment]
Yes, It was a deprecated page that was showing up. It still shows up as the
first result. . https://3t.thinkdesign.com/system-integration/adobe/

Pages we are not building should not be searchable.

**Comment by niravpateldev** [comment]
Now Adobe Page not Appear in Search Results.

**Comment by adam-td** [comment]
Adobe page is not there, thank you.
